import Foundation

/// Localized names share the same category identities as matching and custom input.
nonisolated enum MetadataLocalization {
    static func displayName(_ original: String, language: AppLanguage = .current) -> String {
        let kind: MetadataCategoryKind = original.hasPrefix("tag:") ? .tag : .genre
        let matches = MetadataCategoryRegistry.candidates(original, kind: kind)
        guard matches.count == 1 else { return original }
        let entry = matches[0]
        if language == .english,
           MetadataCategoryRegistry.normalized(original) == MetadataCategoryRegistry.normalized(entry.englishName)
        {
            return original
        }
        let name = entry.name(language: language)
        if MetadataCategoryRegistry.candidates(name, kind: kind).count > 1 {
            return "\(name) (\(entry.englishName))"
        }
        return name
    }

    // Shared by Kavita and AniList, and by both genres and tags.
    // Use exact labels rather than partial matches so custom tags retain their meaning.
    // AniList labels and definitions reviewed via MediaTagCollection on 2026-10-01.
    // Korean display names are maintained by this app, not supplied by AniList.
    static let koreanNames: [String: String] = [
        "action": "액션",
        "adventure": "모험",
        "comedy": "코미디",
        "drama": "드라마",
        "ecchi": "선정적",
        "fantasy": "판타지",
        "hentai": "성인물",
        "horror": "공포",
        "mahou shoujo": "마법소녀",
        "mecha": "메카",
        "music": "음악",
        "mystery": "미스터리",
        "psychological": "심리",
        "romance": "로맨스",
        "sci-fi": "SF",
        "sci fi": "SF",
        "science fiction": "SF",
        "slice of life": "일상",
        "sports": "스포츠",
        "supernatural": "초자연",
        "thriller": "스릴러",
        "historical": "역사",
        "isekai": "이세계",
        "time travel": "시간 여행",
        "time loop": "타임 루프",
        "regression": "회귀",
        "reincarnation": "환생",
        "female protagonist": "여성 주인공",
        "male protagonist": "남성 주인공",
        "overpowered protagonist": "먼치킨 주인공",
        "anti-hero": "안티히어로",
        "villain protagonist": "악역 주인공",
        "villainess": "악녀",
        "non-human protagonist": "인간이 아닌 주인공",
        "android protagonist": "안드로이드 주인공",
        "vampire protagonist": "뱀파이어 주인공",
        "ensemble cast": "군상극",
        "primarily female cast": "여성 중심 등장인물",
        "primarily male cast": "남성 중심 등장인물",
        "primarily adult cast": "성인 중심 등장인물",
        "coming of age": "성장",
        "school": "학교",
        "school club": "학교 동아리",
        "college": "대학",
        "workplace": "직장",
        "office lady": "직장 여성",
        "family life": "가족 생활",
        "parenthood": "부모와 자녀",
        "childcare": "육아",
        "friendship": "우정",
        "found family": "유사 가족",
        "rivalry": "라이벌",
        "team": "팀",
        "companions": "동료",
        "love triangle": "삼각관계",
        "unrequited love": "짝사랑",
        "harem": "하렘",
        "reverse harem": "역하렘",
        "boys' love": "BL",
        "girls' love": "GL",
        "marriage": "결혼",
        "romantic comedy": "로맨틱 코미디",
        "slapstick": "슬랩스틱",
        "satire": "풍자",
        "parody": "패러디",
        "dark comedy": "블랙 코미디",
        "iyashikei": "치유계",
        "tragedy": "비극",
        "revenge": "복수",
        "bullying": "괴롭힘",
        "survival": "생존",
        "disaster": "재난",
        "post-apocalyptic": "포스트 아포칼립스",
        "dystopian": "디스토피아",
        "death game": "데스 게임",
        "battle royale": "배틀 로얄",
        "mind games": "심리전",
        "strategy": "전략",
        "detective": "탐정",
        "investigation": "수사",
        "crime": "범죄",
        "mafia": "마피아",
        "gangs": "갱단",
        "delinquents": "불량배",
        "assassins": "암살자",
        "espionage": "첩보",
        "police": "경찰",
        "military": "군대",
        "war": "전쟁",
        "politics": "정치",
        "succession": "후계자 경쟁",
        "power struggle": "권력 다툼",
        "royalty": "왕족",
        "magic": "마법",
        "witch": "마녀",
        "super power": "초능력",
        "superhero": "슈퍼히어로",
        "martial arts": "무술",
        "swordplay": "검술",
        "wuxia": "무협",
        "cultivation": "수련",
        "dungeon": "던전",
        "dragons": "드래곤",
        "demons": "악마",
        "angels": "천사",
        "gods": "신",
        "vampire": "뱀파이어",
        "vampires": "뱀파이어",
        "zombie": "좀비",
        "zombies": "좀비",
        "ghost": "유령",
        "ghost stories": "괴담",
        "youkai": "요괴",
        "monster girl": "몬스터 소녀",
        "monster boy": "몬스터 소년",
        "gore": "유혈 묘사",
        "body horror": "신체 공포",
        "cyberpunk": "사이버펑크",
        "steampunk": "스팀펑크",
        "space": "우주",
        "aliens": "외계인",
        "robots": "로봇",
        "artificial intelligence": "인공지능",
        "video games": "비디오 게임",
        "virtual world": "가상 세계",
        "board game": "보드게임",
        "card battle": "카드 배틀",
        "cooking": "요리",
        "food": "음식",
        "drawing": "그림",
        "manga making": "만화 제작",
        "writing": "글쓰기",
        "performing arts": "공연 예술",
        "band": "밴드",
        "idol": "아이돌",
        "dancing": "춤",
        "acting": "연기",
        "photography": "사진",
        "fashion": "패션",
        "animals": "동물",
        "pets": "반려동물",
        "travel": "여행",
        "wandering": "방랑",
        "rural": "시골",
        "urban": "도시",
        "medicine": "의학",
        "science": "과학",
        "economics": "경제",
        "educational": "교육",
        "shounen": "소년 만화",
        "shoujo": "소녀 만화",
        "seinen": "청년 만화",
        "josei": "여성 만화",
        "4-koma": "4컷 만화",
        "full color": "풀컬러",
        "long strip": "세로 스크롤",
        "anthology": "앤솔러지",
        "one shot": "단편",
        // Additional AniList tags, including sports, relationships, settings and adult metadata.
        "achromatic": "흑백",
        "achronological order": "비연대기적 구성",
        "acrobatics": "곡예",
        "adoption": "입양",
        "advertisement": "광고",
        "afterlife": "사후 세계",
        "age gap": "나이 차이",
        "age regression": "연령 퇴행",
        "agender": "무성별",
        "agriculture": "농업",
        "ahegao": "아헤가오",
        "airsoft": "에어소프트",
        "alchemy": "연금술",
        "alternate universe": "평행 세계",
        "american football": "미식축구",
        "amnesia": "기억 상실",
        "amputation": "신체 절단",
        "anachronism": "시대착오",
        "anal sex": "항문 성교",
        "ancient china": "고대 중국",
        "anthropomorphism": "의인화",
        "archery": "궁술",
        "armpits": "겨드랑이",
        "aromantic": "무로맨틱",
        "arranged marriage": "정략결혼",
        "asexual": "무성애",
        "ashikoki": "풋잡",
        "asphyxiation": "질식 플레이",
        "astronomy": "천문학",
        "athletics": "육상",
        "augmented reality": "증강 현실",
        "autobiographical": "자전적 이야기",
        "aviation": "항공",
        "badminton": "배드민턴",
        "ballet": "발레",
        "bar": "술집",
        "baseball": "야구",
        "basketball": "농구",
        "biographical": "전기",
        "bisexual": "양성애",
        "blackmail": "협박",
        "boarding school": "기숙학교",
        "body image": "신체 이미지",
        "body swapping": "신체 교환",
        "bondage": "속박 플레이",
        "boobjob": "파이즈리",
        "bowling": "볼링",
        "boxing": "복싱",
        "brainwashing": "세뇌",
        "butler": "집사",
        "calligraphy": "서예",
        "camping": "캠핑",
        "cannibalism": "식인",
        "cars": "자동차",
        "centaur": "켄타우로스",
        "cervix penetration": "자궁경부 삽입",
        "cgi": "컴퓨터 그래픽",
        "cheating": "외도",
        "cheerleading": "치어리딩",
        "chibi": "SD 캐릭터",
        "chimera": "키메라",
        "chuunibyou": "중2병",
        "circus": "서커스",
        "class struggle": "계급 갈등",
        "classic literature": "고전 문학",
        "classical music": "클래식 음악",
        "clone": "복제체",
        "coastal": "해안 지역",
        "cohabitation": "동거",
        "conspiracy": "음모",
        "cosmic horror": "우주적 공포",
        "cosplay": "코스프레",
        "cowboys": "카우보이",
        "creature taming": "생물 길들이기",
        "criminal organization": "범죄 조직",
        "crossdressing": "크로스드레싱",
        "crossover": "크로스오버",
        "cult": "사이비 집단",
        "cumflation": "정액 팽창",
        "cunnilingus": "커닐링구스",
        "curses": "저주",
        "cute boys doing cute things": "귀여운 소년들의 일상",
        "cute girls doing cute things": "귀여운 소녀들의 일상",
        "cyborg": "사이보그",
        "cycling": "사이클",
        "deepthroat": "딥스로트",
        "defloration": "첫 성경험(여성)",
        "denpa": "전파계",
        "desert": "사막",
        "dilf": "중년 남성 성애",
        "dinosaurs": "공룡",
        "disability": "장애",
        "dissociative identities": "해리성 정체성",
        "double penetration": "이중 삽입",
        "drugs": "마약",
        "dullahan": "듀라한",
        "e-sports": "이스포츠",
        "eco-horror": "생태 공포",
        "elderly protagonist": "노년 주인공",
        "elf": "엘프",
        "environmental": "환경",
        "episodic": "에피소드식 구성",
        "ero guro": "에로 그로",
        "erotic piercings": "성적 피어싱",
        "estranged family": "소원해진 가족",
        "exhibitionism": "노출증",
        "exiled": "추방",
        "exorcism": "퇴마",
        "facial": "안면 사정",
        "fairy": "요정",
        "fairy tale": "동화",
        "fake relationship": "가짜 연애",
        "feet": "발",
        "fellatio": "펠라치오",
        "female harem": "여성 하렘",
        "femboy": "여성적인 남성",
        "femdom": "여성 지배",
        "fencing": "펜싱",
        "filmmaking": "영화 제작",
        "fingering": "손가락 삽입",
        "firefighters": "소방관",
        "fishing": "낚시",
        "fisting": "피스팅",
        "fitness": "피트니스",
        "flash": "플래시 애니메이션",
        "flat chest": "작은 가슴",
        "football": "축구",
        "foreign": "해외 배경",
        "fugitive": "도망자",
        "full cgi": "전체 컴퓨터 그래픽",
        "futanari": "후타나리",
        "gambling": "도박",
        "gekiga": "극화",
        "gender bending": "성별 전환",
        "go": "바둑",
        "goblin": "고블린",
        "golf": "골프",
        "graduation project": "졸업 작품",
        "group sex": "집단 성교",
        "guns": "총기",
        "gyaru": "갸루",
        "hair pulling": "머리카락 당기기",
        "handball": "핸드볼",
        "handjob": "핸드잡",
        "henshin": "변신",
        "heterosexual": "이성애",
        "hikikomori": "히키코모리",
        "hip-hop music": "힙합 음악",
        "homeless": "노숙",
        "horticulture": "원예",
        "human experimentation": "인체 실험",
        "human pet": "인간 펫",
        "hypersexuality": "성욕 과다",
        "ice sports": "빙상 스포츠",
        "incest": "근친 관계",
        "indigenous cultures": "원주민 문화",
        "inn": "여관",
        "inseki": "비혈연 가족 간 연애",
        "interspecies": "이종 간 연애",
        "irrumatio": "이루마치오",
        "jazz music": "재즈 음악",
        "judo": "유도",
        "kabuki": "가부키",
        "kaiju": "거대 괴수",
        "karuta": "카루타",
        "kemonomimi": "동물 귀",
        "kids": "아동 대상",
        "kingdom management": "왕국 경영",
        "konbini": "편의점",
        "kuudere": "쿨데레",
        "lacrosse": "라크로스",
        "lactation": "모유",
        "language barrier": "언어 장벽",
        "large breasts": "큰 가슴",
        "lgbtq+ themes": "성소수자 주제",
        "lost civilization": "잃어버린 문명",
        "mahjong": "마작",
        "maids": "메이드",
        "makeup": "메이크업",
        "male harem": "남성 하렘",
        "male pregnancy": "남성 임신",
        "manzai": "만자이",
        "masochism": "마조히즘",
        "masturbation": "자위",
        "matchmaking": "중매",
        "mating press": "메이팅 프레스",
        "matriarchy": "여성 중심 사회",
        "medieval": "중세",
        "memory manipulation": "기억 조작",
        "mermaid": "인어",
        "meta": "메타",
        "metal music": "메탈 음악",
        "middle east": "중동",
        "milf": "중년 여성 성애",
        "mixed gender harem": "혼성 하렘",
        "mixed media": "혼합 매체",
        "modeling": "모델 활동",
        "mopeds": "모페드",
        "motorcycles": "오토바이",
        "mountaineering": "등산",
        "musical theater": "뮤지컬",
        "mythology": "신화",
        "nakadashi": "질내 사정",
        "natural disaster": "자연재해",
        "necromancy": "강령술",
        "nekomimi": "고양이 귀",
        "netorare": "네토라레",
        "netorase": "네토라세",
        "netori": "네토리",
        "ninja": "닌자",
        "no dialogue": "대사 없음",
        "noir": "누아르",
        "non-fiction": "논픽션",
        "nudity": "노출",
        "nun": "수녀",
        "office": "사무실",
        "oiran": "오이란",
        "ojou-sama": "아가씨 캐릭터",
        "omegaverse": "오메가버스",
        "orphan": "고아",
        "otaku culture": "오타쿠 문화",
        "outdoor activities": "야외 활동",
        "oyakodon": "모녀 성관계",
        "pandemic": "감염병 대유행",
        "parkour": "파쿠르",
        "pet play": "펫 플레이",
        "philosophy": "철학",
        "pirates": "해적",
        "poker": "포커",
        "polyamorous": "폴리아모리",
        "pov": "1인칭 시점",
        "pregnancy": "임신",
        "primarily animal cast": "동물 중심 등장인물",
        "primarily child cast": "어린이 중심 등장인물",
        "primarily teen cast": "청소년 중심 등장인물",
        "prison": "감옥",
        "prophecy": "예언",
        "prostitution": "성매매",
        "proxy battle": "대리 전투",
        "psychosexual": "성 심리",
        "public sex": "공공장소 성행위",
        "puppetry": "인형극",
        "rakugo": "라쿠고",
        "rape": "강간",
        "real robot": "리얼 로봇",
        "rehabilitation": "재활",
        "religion": "종교",
        "rescue": "구조 활동",
        "restaurant": "음식점",
        "reverse isekai": "역이세계",
        "rimjob": "항문 구강 성교",
        "rock music": "록 음악",
        "rotoscoping": "로토스코핑",
        "royal affairs": "왕실 정치",
        "rugby": "럭비",
        "sadism": "사디즘",
        "samurai": "사무라이",
        "scat": "배설물 성애",
        "scissoring": "시저링",
        "scuba diving": "스쿠버 다이빙",
        "sex toys": "성인용품",
        "shapeshifting": "형태 변환",
        "shimaidon": "자매 성관계",
        "ships": "선박",
        "shogi": "쇼기",
        "short-form chapter": "초단편 챕터",
        "shrine maiden": "무녀",
        "sixty-nine": "69 체위",
        "skateboarding": "스케이트보드",
        "skeleton": "해골",
        "slavery": "노예제",
        "snowscape": "설경",
        "software development": "소프트웨어 개발",
        "space opera": "스페이스 오페라",
        "spearplay": "창술",
        "squirting": "여성 사정",
        "stop motion": "스톱 모션",
        "strap-on": "스트랩온",
        "succubus": "서큐버스",
        "suicide": "자살",
        "sumata": "스마타",
        "sumo": "스모",
        "super robot": "슈퍼 로봇",
        "surfing": "서핑",
        "surreal comedy": "초현실 코미디",
        "swapping": "파트너 교환",
        "sweat": "땀",
        "swimming": "수영",
        "table tennis": "탁구",
        "tanks": "전차",
        "tanned skin": "그을린 피부",
        "teacher": "교사",
        "teens' love": "TL 로맨스",
        "tennis": "테니스",
        "tentacles": "촉수",
        "terrorism": "테러",
        "threesome": "3인 성관계",
        "time manipulation": "시간 조작",
        "time skip": "시간 건너뛰기",
        "tokusatsu": "특촬",
        "tomboy": "보이시한 여성",
        "torture": "고문",
        "trains": "기차",
        "transgender": "트랜스젠더",
        "triads": "삼합회",
        "tsundere": "츤데레",
        "twins": "쌍둥이",
        "urban fantasy": "도시 판타지",
        "vertical video": "세로형 영상",
        "veterinarian": "수의사",
        "vikings": "바이킹",
        "virginity": "첫 성경험(남성)",
        "vocal synth": "음성 합성 보컬",
        "volleyball": "배구",
        "vore": "포식 성애",
        "voyeur": "관음",
        "vtuber": "버추얼 유튜버",
        "watersports": "소변 플레이",
        "werewolf": "늑대인간",
        "wilderness": "야생 환경",
        "work": "직업",
        "wrestling": "레슬링",
        "yakuza": "야쿠자",
        "yandere": "얀데레",
        "yuri": "백합",
        "zoophilia": "동물 성애",
    ]
}
